### ISSUE TITLE
kendo-angular-grid 3.0.0 Cannot read property 'subscribe' of undefined

### ISSUE THREAD

**Issue by ArnoMyOnlinePresence** [telerik/kendo-angular#1470]
I'm submitting a bug after upgrading from 1.7.2 to 3.0.0

## Current behavior
on grid load i get the following 2 errros
core.js:1427 ERROR TypeError: Cannot read property 'subscribe' of undefined
    at new GridComponent (grid.component.js:298)
    at createClass (core.js:12480)
    at createDirectiveInstance (core.js:12315)
    at createViewNodes (core.js:13776)
    at callViewAction (core.js:14210)
    at execComponentViewsAction (core.js:14119)
    at createViewNodes (core.js:13804)
    at createRootView (core.js:13665)
    at Object.createProdRootView [as createRootView] (core.js:14358)
    at ComponentFactory_.create (core.js:11260)

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'subscribe' of undefined
TypeError: Cannot read property 'subscribe' of undefined
    at new GridComponent (grid.component.js:298)
    at createClass (core.js:12480)
    at createDirectiveInstance (core.js:12315)
    at createViewNodes (core.js:13776)
    at callViewAction (core.js:14210)
    at execComponentViewsAction (core.js:14119)
    at createViewNodes (core.js:13804)
    at createRootView (core.js:13665)
    at Object.createProdRootView [as createRootView] (core.js:14358)
    at ComponentFactory_.create (core.js:11260)
    at new GridComponent (grid.component.js:298)
    at createClass (core.js:12480)
    at createDirectiveInstance (core.js:12315)
    at createViewNodes (core.js:13776)
    at callViewAction (core.js:14210)
    at execComponentViewsAction (core.js:14119)
    at createViewNodes (core.js:13804)
    at createRootView (core.js:13665)
    at Object.createProdRootView [as createRootView] (core.js:14358)
    at ComponentFactory_.create (core.js:11260)
    at resolvePromise (zone.js:821)
    at resolvePromise (zone.js:785)
    at eval (zone.js:870)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4744)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:594)
    at ZoneTask.invokeTask [as invoke] (zone.js:499)
    at invokeTask (zone.js:1536)

## Expected behavior
It should build the Grid without any problems

## Environment
Angular 5
Package versions:
```
+-- @angular/animations@5.2.4
+-- @angular/cli@1.6.3
+-- @angular/common@5.1.3
+-- @angular/compiler@5.1.3
+-- @angular/compiler-cli@5.1.3
+-- UNMET PEER DEPENDENCY @angular/core@5.1.3
+-- @angular/forms@5.1.3
+-- @angular/http@5.1.3
+-- @angular/language-service@5.1.3
+-- @angular/platform-browser@5.1.3
+-- @angular/platform-browser-dynamic@5.1.3
+-- @angular/router@5.1.3
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-buttons@3.0.1
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-dateinputs@1.4.4
+-- @progress/kendo-angular-dialog@3.0.0
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-dropdowns@1.6.1
+-- @progress/kendo-angular-excel-export@1.0.5
+-- @progress/kendo-angular-grid@3.0.0
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-inputs@1.5.0
+-- @progress/kendo-angular-intl@1.3.0
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-l10n@1.0.5
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-popup@^2.0.0
+-- @progress/kendo-data-query@1.1.2
+-- @progress/kendo-drawing@1.4.1
+-- @progress/kendo-theme-default@2.47.1
+-- @types/jasmine@2.5.54
+-- @types/jasminewd2@2.0.3
+-- @types/jquery@3.2.17
+-- @types/node@6.0.96
+-- angular2-notifications@0.9.7
+-- bootstrap@4.0.0-beta.3
+-- codelyzer@4.0.2
+-- core-js@2.5.3
+-- dropzone@5.4.0
+-- fingerprintjs2@1.6.1
+-- font-awesome@4.7.0
+-- jasmine-core@2.6.4
+-- jasmine-spec-reporter@4.1.1
+-- jquery@3.2.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.1.1
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.3
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- moment@2.20.1
+-- ng-push@0.2.1
+-- ngx-img-cropper@0.9.7
+-- ngx-qrcode2@0.0.5
+-- UNMET PEER DEPENDENCY popper.js@^1.12.9
+-- protractor@5.1.2
+-- UNMET PEER DEPENDENCY rxjs@5.5.6
+-- table-dragger@1.0.2
+-- ts-node@3.2.2
+-- tslint@5.7.0
+-- UNMET PEER DEPENDENCY typescript@2.7.2
+-- underscore@1.8.3
+-- zone.js@0.8.19
```

Browser:

- Chrome (desktop) version 65.0.3325.181

System:
- TypeScript version: XX 
- Node version: node -v = 8.11 ; npm -v = 5.6.0
- Platform:  Windows

`<kendo-grid [data]="data" [pageSize]="pageSize" [sortable]="true" [skip]="skip" [scrollable]="'none'" (pageChange)="pageChange($event)"
        [sort]="sort" [sortable]="{ allowUnsort: allowUnsort, mode: multiple ? 'multiple' : 'single' }" (sortChange)="sortChange($event)"
        [pageable]="{
          pageSizes: pageSizes
        }">
        <kendo-grid-column field="fullName" title="Full Name" width="200">
          <ng-template kendoGridCellTemplate let-dataItem>
            <span class="whole-cell">
              <a [routerLink]="['edit',dataItem.id]">{{ dataItem.fullName }}</a>
            </span>
          </ng-template>
        </kendo-grid-column>
        <kendo-grid-column field="email" title="Email Address" width="200"></kendo-grid-column>
        <kendo-grid-column field="mobileNumber" title="Mobile Number" width="100"></kendo-grid-column>
        <kendo-grid-column field="dateRegistered" title="Date Registered" width="200"></kendo-grid-column>
        <kendo-grid-column field="lastLoginDate" title="Last Login Date" width="200"></kendo-grid-column>
        <kendo-grid-column width="100">
          <ng-template kendoGridCellTemplate let-dataItem>
            <span class="whole-cell">
              <a *ngIf="canUserEdit" title="Edit user" [routerLink]="['edit',dataItem.id]">
                <i class="fa fa-edit"></i>
              </a>
              <a *ngIf="canUserAssignPermissions" title="Set user permissions" class="anchor" [routerLink]="['/permissions',dataItem.id,true]">
                <i class="fa fa-minus-circle"></i>
              </a>
              <a class="anchor" (click)="toggleUserStatusUpdateConfirmation(dataItem)">
                <i class="fa {{ getNewUserStatusIcon(dataItem) }}" title="{{ getUserNewStatusText(dataItem) }}"></i>
              </a>
              <a *ngIf="canUserDelete" class="anchor" title="Delete user" (click)="confirmUserDelete(dataItem)">
                <i class="fa fa-trash-o"></i>
              </a>
            </span>
          </ng-template>
        </kendo-grid-column>
      </kendo-grid>`

The data is a normal Kendo GridDataResult

**Comment by ggkrustev** [comment]
Hi @ArnoMyOnlinePresence, 

Based on the shared stack-trace, I assume that some of the required peer dependencies are not installed correctly. In general, all warnings about **unmet peer dependencies** should be resolved before build the project successfully.

Looking at the dependencies list, I noticed that there is a unmet RxJS dependency. Note that the latest Grid (3.x.x) version requires RxJS@5.5.6 or greater.

**Comment by ArnoMyOnlinePresence** [comment]
Hi @ggkrustev 

Thanks for getting back to me so quickly.

What is the best way to resolve these dependencies as npm install doesn't seem to solve it.
Will look intorxjs
