### ISSUE TITLE
Property 'fromPromise' does not exist on type 'typeof Observable'

### ISSUE THREAD

**Issue by graphicsxp** [telerik/kendo-angular#1416]
* Bug report 

After upgrading kendo-angular-dropdowns from 1.6.1 to 2.1.0, I can no longer build my application. 

## Current behavior

when running ng build I get the following error wherever fromPromise is used  : 
- Property 'fromPromise' does not exist on type 'typeof Observable'.

## Expected behavior

it should build

## Minimal reproduction of the problem with instructions

any project with kendo-angular-dropdowns 2.1.0 and rxjs 5.5.8.

import is done as follow : 

    import { Observable } from 'rxjs/Observable';

**Comment by rusev** [comment]
This is related to the introduction of [pipeable operators](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md) starting from version `5.5.x`. You can find more details here - https://stackoverflow.com/a/45785513/1393172

**Comment by tsvetomir** [comment]
To add some background, `fromPromise` was added to the Observable prototype by our code. This is how imports in RxJS < 5.5 work. Since we moved to pipeable operators (see #1244) you now have to make sure all operators that you use are imported in your code, as we no longer modify the Observable prototype.
